output   = "generated/models"
wipe     = true
no-tests = true
always-wrap-errors = true

[mysql]
user    = "root"
pass    = "pass"
host    = "127.0.0.1"
port    = 13306
dbname  = "test"
sslmode = "false"

